language: elixir
elixir: 1.2.0
otp_release:
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
script: mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
